// <auto-generated/>

using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("Paket.VisualStudio.Tests")]
[assembly: AssemblyTitle("Paket.VisualStudio")]
[assembly: AssemblyProduct("Paket.VisualStudio")]
[assembly: AssemblyDescription("Manage your Paket dependencies from Visual Studio!")]
[assembly: AssemblyVersion("0.23.2")]
[assembly: AssemblyFileVersion("0.23.2")]
namespace Paket.VisualStudio.Properties {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.23.2";
        internal const string InformationalVersion = "0.23.2";
    }
}
